import { CellColor, Cell } from "../Types/Types";

export const attemptsArray: Cell[][] = [
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
];
