import { CellState } from "../Types/Types";

export const attemptsArray: CellState[][] = [
  [
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
  ],
  [
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
  ],
  [
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
  ],
  [
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
  ],
  [
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
  ],
  [
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
    { content: "", color: "plain" },
  ],
];
