import { CellColor, CellState } from "../Types/Types";

export const attemptsArray: CellState[][] = [
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
  [
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
    { content: "", color: CellColor.plain },
  ],
];
